plot(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(diameter(ba),diameter(ba_1),diameter(ba_2),diameter(ba_3),diameter(ba_4),diameter(ba_5),diameter(ba_6),diameter(ba_7),diameter(ba_8),diameter(ba_9),diameter(ba_10),diameter(ba_15),diameter(ba_20),diameter(ba_25)),xlab="Percentage", ylab="Diameter",ylim=c(0,30),col="blue", type="l")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(diameter(ws),diameter(ws_1),diameter(ws_2),diameter(ws_3),diameter(ws_4),diameter(ws_5),diameter(ws_6),diameter(ws_7),diameter(ws_8),diameter(ws_9),diameter(ws_10),diameter(ws_15),diameter(ws_20),diameter(ws_25)),col="green")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(diameter(er),diameter(er_1),diameter(er_2),diameter(er_3),diameter(er_4),diameter(er_5),diameter(er_6),diameter(er_7),diameter(er_8),diameter(er_9),diameter(er_10),diameter(er_15),diameter(er_20),diameter(er_25)), col="red")
#Red -> er ; Blue -> ba ; Green -> ws

plot(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(diameter(ba),diameter(ba_ataque_1),diameter(ba_ataque_2),diameter(ba_ataque_3),diameter(ba_ataque_4),diameter(ba_ataque_5),diameter(ba_ataque_6),diameter(ba_ataque_7),diameter(ba_ataque_8),diameter(ba_ataque_9),diameter(ba_ataque_10),diameter(ba_ataque_15),diameter(ba_ataque_20),diameter(ba_ataque_25)),xlab="Percentage", ylab="Diameter",ylim=c(0,40),col="blue", type="l")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(diameter(ws),diameter(ws_ataque_1),diameter(ws_ataque_2),diameter(ws_ataque_3),diameter(ws_ataque_4),diameter(ws_ataque_5),diameter(ws_ataque_6),diameter(ws_ataque_7),diameter(ws_ataque_8),diameter(ws_ataque_9),diameter(ws_ataque_10),diameter(ws_ataque_15),diameter(ws_ataque_20),diameter(ws_ataque_25)),col="green")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(diameter(er),diameter(er_ataque_1),diameter(er_ataque_2),diameter(er_ataque_3),diameter(er_ataque_4),diameter(er_ataque_5),diameter(er_ataque_6),diameter(er_ataque_7),diameter(er_ataque_8),diameter(er_ataque_9),diameter(er_ataque_10),diameter(er_ataque_15),diameter(er_ataque_20),diameter(er_ataque_25)), col="red")

#avg.degree

sum(degree(ba))/vcount(ba)
#Aleatorio
plot(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(sum(degree(ba))/vcount(ba),sum(degree(ba_1))/vcount(ba_1),sum(degree(ba_2))/vcount(ba_2),sum(degree(ba_3))/vcount(ba_3),sum(degree(ba_4))/vcount(ba_4),sum(degree(ba_5))/vcount(ba_5),sum(degree(ba_6))/vcount(ba_6),sum(degree(ba_7))/vcount(ba_7),sum(degree(ba_8))/vcount(ba_8),sum(degree(ba_9))/vcount(ba_9),sum(degree(ba_10))/vcount(ba_10),sum(degree(ba_15))/vcount(ba_15),sum(degree(ba_20))/vcount(ba_20),sum(degree(ba_25))/vcount(ba_25)),xlab="Percentage", ylab="Avg. Degree",ylim=c(0,3),col="blue", type="l")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(sum(degree(ws))/vcount(ws),sum(degree(ws_1))/vcount(ws_1),sum(degree(ws_2))/vcount(ws_2),sum(degree(ws_3))/vcount(ws_3),sum(degree(ws_4))/vcount(ws_4),sum(degree(ws_5))/vcount(ws_5),sum(degree(ws_6))/vcount(ws_6),sum(degree(ws_7))/vcount(ws_7),sum(degree(ws_8))/vcount(ws_8),sum(degree(ws_9))/vcount(ws_9),sum(degree(ws_10))/vcount(ws_10),sum(degree(ws_15))/vcount(ws_15),sum(degree(ws_20))/vcount(ws_20),sum(degree(ws_25))/vcount(ws_25)),col="green")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(sum(degree(er))/vcount(er),sum(degree(er_1))/vcount(er_1),sum(degree(er_2))/vcount(er_2),sum(degree(er_3))/vcount(er_3),sum(degree(er_4))/vcount(er_4),sum(degree(er_5))/vcount(er_5),sum(degree(er_6))/vcount(er_6),sum(degree(er_7))/vcount(er_7),sum(degree(er_8))/vcount(er_8),sum(degree(er_9))/vcount(er_9),sum(degree(er_10))/vcount(er_10),sum(degree(er_15))/vcount(er_15),sum(degree(er_20))/vcount(er_20),sum(degree(er_25))/vcount(er_25)),col="red")
#Ataque
plot(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(sum(degree(ba))/vcount(ba),sum(degree(ba_ataque_1))/vcount(ba_ataque_1),sum(degree(ba_ataque_2))/vcount(ba_ataque_2),sum(degree(ba_ataque_3))/vcount(ba_ataque_3),sum(degree(ba_ataque_4))/vcount(ba_ataque_4),sum(degree(ba_ataque_5))/vcount(ba_ataque_5),sum(degree(ba_ataque_6))/vcount(ba_ataque_6),sum(degree(ba_ataque_7))/vcount(ba_ataque_7),sum(degree(ba_ataque_8))/vcount(ba_ataque_8),sum(degree(ba_ataque_9))/vcount(ba_ataque_9),sum(degree(ba_ataque_10))/vcount(ba_ataque_10),sum(degree(ba_ataque_15))/vcount(ba_ataque_15),sum(degree(ba_ataque_20))/vcount(ba_ataque_20),sum(degree(ba_ataque_25))/vcount(ba_ataque_25)),xlab="Percentage", ylab="Avg. Degree",ylim=c(0,2),col="blue", type="l")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(sum(degree(ws))/vcount(ws),sum(degree(ws_ataque_1))/vcount(ws_ataque_1),sum(degree(ws_ataque_2))/vcount(ws_ataque_2),sum(degree(ws_ataque_3))/vcount(ws_ataque_3),sum(degree(ws_ataque_4))/vcount(ws_ataque_4),sum(degree(ws_ataque_5))/vcount(ws_ataque_5),sum(degree(ws_ataque_6))/vcount(ws_ataque_6),sum(degree(ws_ataque_7))/vcount(ws_ataque_7),sum(degree(ws_ataque_8))/vcount(ws_ataque_8),sum(degree(ws_ataque_9))/vcount(ws_ataque_9),sum(degree(ws_ataque_10))/vcount(ws_ataque_10),sum(degree(ws_ataque_15))/vcount(ws_ataque_15),sum(degree(ws_ataque_20))/vcount(ws_ataque_20),sum(degree(ws_ataque_25))/vcount(ws_ataque_25)),col="green")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(sum(degree(er))/vcount(er),sum(degree(er_ataque_1))/vcount(er_ataque_1),sum(degree(er_ataque_2))/vcount(er_ataque_2),sum(degree(er_ataque_3))/vcount(er_ataque_3),sum(degree(er_ataque_4))/vcount(er_ataque_4),sum(degree(er_ataque_5))/vcount(er_ataque_5),sum(degree(er_ataque_6))/vcount(er_ataque_6),sum(degree(er_ataque_7))/vcount(er_ataque_7),sum(degree(er_ataque_8))/vcount(er_ataque_8),sum(degree(er_ataque_9))/vcount(er_ataque_9),sum(degree(er_ataque_10))/vcount(er_ataque_10),sum(degree(er_ataque_15))/vcount(er_ataque_15),sum(degree(er_ataque_20))/vcount(er_ataque_20),sum(degree(er_ataque_25))/vcount(er_ataque_25)),col="red")


#Size of the giant component

(clusters(ba))$csize[1]

#Aleatorio
plot(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c((clusters(ba))$csize[1],(clusters(ba_1))$csize[1],(clusters(ba_2))$csize[1],(clusters(ba_3))$csize[1],(clusters(ba_4))$csize[1],(clusters(ba_5))$csize[1],(clusters(ba_6))$csize[1],(clusters(ba_7))$csize[1],(clusters(ba_8))$csize[1],(clusters(ba_9))$csize[1],(clusters(ba_10))$csize[1],(clusters(ba_15))$csize[1],(clusters(ba_20))$csize[1],(clusters(ba_25))$csize[1]),xlab="Percentage", ylab="Size of Giant Component",ylim=c(0,1000),col="blue", type="l")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c((clusters(ws))$csize[1],(clusters(ws_1))$csize[1],(clusters(ws_2))$csize[1],(clusters(ws_3))$csize[1],(clusters(ws_4))$csize[1],(clusters(ws_5))$csize[1],(clusters(ws_6))$csize[1],(clusters(ws_7))$csize[1],(clusters(ws_8))$csize[1],(clusters(ws_9))$csize[1],(clusters(ws_10))$csize[1],(clusters(ws_15))$csize[1],(clusters(ws_20))$csize[1],(clusters(ws_25))$csize[1]),col="green")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c((clusters(er))$csize[1],(clusters(er_1))$csize[1],(clusters(er_2))$csize[1],(clusters(er_3))$csize[1],(clusters(er_4))$csize[1],(clusters(er_5))$csize[1],(clusters(er_6))$csize[1],(clusters(er_7))$csize[1],(clusters(er_8))$csize[1],(clusters(er_9))$csize[1],(clusters(er_10))$csize[1],(clusters(er_15))$csize[1],(clusters(er_20))$csize[1],(clusters(er_25))$csize[1]),col="red")
#Ataque
plot(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c((clusters(ba))$csize[1],(clusters(ba_ataque_1))$csize[1],(clusters(ba_ataque_2))$csize[1],(clusters(ba_ataque_3))$csize[1],(clusters(ba_ataque_4))$csize[1],(clusters(ba_ataque_5))$csize[1],(clusters(ba_ataque_6))$csize[1],(clusters(ba_ataque_7))$csize[1],(clusters(ba_ataque_8))$csize[1],(clusters(ba_ataque_9))$csize[1],(clusters(ba_ataque_10))$csize[1],(clusters(ba_ataque_15))$csize[1],(clusters(ba_ataque_20))$csize[1],(clusters(ba_ataque_25))$csize[1]),xlab="Percentage", ylab="Size of Giant Component",ylim=c(0,1000),col="blue", type="l")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c((clusters(ws))$csize[1],(clusters(ws_ataque_1))$csize[1],(clusters(ws_ataque_2))$csize[1],(clusters(ws_ataque_3))$csize[1],(clusters(ws_ataque_4))$csize[1],(clusters(ws_ataque_5))$csize[1],(clusters(ws_ataque_6))$csize[1],(clusters(ws_ataque_7))$csize[1],(clusters(ws_ataque_8))$csize[1],(clusters(ws_ataque_9))$csize[1],(clusters(ws_ataque_10))$csize[1],(clusters(ws_ataque_15))$csize[1],(clusters(ws_ataque_20))$csize[1],(clusters(ws_ataque_25))$csize[1]),col="green")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c((clusters(er))$csize[1],(clusters(er_ataque_1))$csize[1],(clusters(er_ataque_2))$csize[1],(clusters(er_ataque_3))$csize[1],(clusters(er_ataque_4))$csize[1],(clusters(er_ataque_5))$csize[1],(clusters(er_ataque_6))$csize[1],(clusters(er_ataque_7))$csize[1],(clusters(er_ataque_8))$csize[1],(clusters(er_ataque_9))$csize[1],(clusters(er_ataque_10))$csize[1],(clusters(er_ataque_15))$csize[1],(clusters(er_ataque_20))$csize[1],(clusters(er_ataque_25))$csize[1]),col="red")


#Betweenness
centralization.betweenness(ba)$centralization

#Aleatorio
plot(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(centralization.betweenness(ba)$centralization,centralization.betweenness(ba_1)$centralization,centralization.betweenness(ba_2)$centralization,centralization.betweenness(ba_3)$centralization,centralization.betweenness(ba_4)$centralization,centralization.betweenness(ba_5)$centralization,centralization.betweenness(ba_6)$centralization,centralization.betweenness(ba_7)$centralization,centralization.betweenness(ba_8)$centralization,centralization.betweenness(ba_9)$centralization,centralization.betweenness(ba_10)$centralization,centralization.betweenness(ba_15)$centralization,centralization.betweenness(ba_20)$centralization,centralization.betweenness(ba_25)$centralization),xlab="Percentage", ylab="Betweenness",ylim=c(0,0.07),col="blue", type="l")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(centralization.betweenness(ws)$centralization,centralization.betweenness(ws_1)$centralization,centralization.betweenness(ws_2)$centralization,centralization.betweenness(ws_3)$centralization,centralization.betweenness(ws_4)$centralization,centralization.betweenness(ws_5)$centralization,centralization.betweenness(ws_6)$centralization,centralization.betweenness(ws_7)$centralization,centralization.betweenness(ws_8)$centralization,centralization.betweenness(ws_9)$centralization,centralization.betweenness(ws_10)$centralization,centralization.betweenness(ws_15)$centralization,centralization.betweenness(ws_20)$centralization,centralization.betweenness(ws_25)$centralization),col="green")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(centralization.betweenness(er)$centralization,centralization.betweenness(er_1)$centralization,centralization.betweenness(er_2)$centralization,centralization.betweenness(er_3)$centralization,centralization.betweenness(er_4)$centralization,centralization.betweenness(er_5)$centralization,centralization.betweenness(er_6)$centralization,centralization.betweenness(er_7)$centralization,centralization.betweenness(er_8)$centralization,centralization.betweenness(er_9)$centralization,centralization.betweenness(er_10)$centralization,centralization.betweenness(er_15)$centralization,centralization.betweenness(er_20)$centralization,centralization.betweenness(er_25)$centralization),col="red")
#Ataque
plot(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(centralization.betweenness(ba)$centralization,centralization.betweenness(ba_ataque_1)$centralization,centralization.betweenness(ba_ataque_2)$centralization,centralization.betweenness(ba_ataque_3)$centralization,centralization.betweenness(ba_ataque_4)$centralization,centralization.betweenness(ba_ataque_5)$centralization,centralization.betweenness(ba_ataque_6)$centralization,centralization.betweenness(ba_ataque_7)$centralization,centralization.betweenness(ba_ataque_8)$centralization,centralization.betweenness(ba_ataque_9)$centralization,centralization.betweenness(ba_ataque_10)$centralization,centralization.betweenness(ba_ataque_15)$centralization,centralization.betweenness(ba_ataque_20)$centralization,centralization.betweenness(ba_ataque_25)$centralization),xlab="Percentage", ylab="Betweenness",ylim=c(0,0.12),col="blue", type="l")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(centralization.betweenness(ws)$centralization,centralization.betweenness(ws_ataque_1)$centralization,centralization.betweenness(ws_ataque_2)$centralization,centralization.betweenness(ws_ataque_3)$centralization,centralization.betweenness(ws_ataque_4)$centralization,centralization.betweenness(ws_ataque_5)$centralization,centralization.betweenness(ws_ataque_6)$centralization,centralization.betweenness(ws_ataque_7)$centralization,centralization.betweenness(ws_ataque_8)$centralization,centralization.betweenness(ws_ataque_9)$centralization,centralization.betweenness(ws_ataque_10)$centralization,centralization.betweenness(ws_ataque_15)$centralization,centralization.betweenness(ws_ataque_20)$centralization,centralization.betweenness(ws_ataque_25)$centralization),col="green")
lines(c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0,2.5),c(centralization.betweenness(er)$centralization,centralization.betweenness(er_ataque_1)$centralization,centralization.betweenness(er_ataque_2)$centralization,centralization.betweenness(er_ataque_3)$centralization,centralization.betweenness(er_ataque_4)$centralization,centralization.betweenness(er_ataque_5)$centralization,centralization.betweenness(er_ataque_6)$centralization,centralization.betweenness(er_ataque_7)$centralization,centralization.betweenness(er_ataque_8)$centralization,centralization.betweenness(er_ataque_9)$centralization,centralization.betweenness(er_ataque_10)$centralization,centralization.betweenness(er_ataque_15)$centralization,centralization.betweenness(er_ataque_20)$centralization,centralization.betweenness(er_ataque_25)$centralization),col="red")

